language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
    - travis_retry pip install -U pip wheel
    - travis_retry pip install setuptools==24.0.3
    - travis_retry pip install --ignore-installed -r requirements.txt
script: py.test
